api_platform:
    title: MyExpenses 
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        jsonapi: ['application/vnd.api+json']
        json: ['application/json']
        xml: ['application/xml', 'text/xml']
        yaml: ['application/x-yaml']
        csv: ['text/csv']
        html: ['text/html']
    collection:
        pagination:
          enabled: true
          enabled_parameter_name: pagination
    patch_formats:
        json: ['application/merge-patch+json']
        jsonapi: ['application/vnd.api+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    # Good cache defaults for REST APIs
    defaults:
        pagination_enabled: true
        pagination_client_enabled: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']